server:
  # 端口
  port: 8081

#连接数据库信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1234
    hikari:
      # 连接池名
      pool-name: DateHikariCp
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认为600000（10分钟）
      idle-timeout: 180000
      # 最大连接数,默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认为1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  #Redis配置
  redis:
    # 连接超时时间
    timeout: 10000ms
    # Redis服务器地址
    host: localhost
    # Redis服务器端口
    port: 6379
    # 选择哪个库，默认0库
    database: 0
    lettuce:
      pool:
        max-active: 1024 # 最大连接数，默认 8
        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200 # 最大空闲连接，默认为 8
        min-idle: 5 # 最小空闲连接，默认为 0

# Mybatis-plus配置
mybatis-plus:
  # 配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.lp.server.entity
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false

# MyBatis SQL 打印（方法接口所在的包）
logging:
  level:
    com.lp.server.mapper: debug

jwt:
  # JWT 存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密匙
  secret: yeb-secret
  # JWT 超期限时间（60*60*24）
  expiration: 604800
  # JWT 负载中拿到开头
  tokenHead: Bearer